# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_auto_20160404_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicegenerationrecord',
            name='ledger',
        ),
        migrations.DeleteModel(
            name='InvoiceGenerationRecord',
        ),
    ]
