# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 21:02
from __future__ import unicode_literals

from django.db import migrations, models


def set_ledger_number_field_to_primary_key_value(apps, schema_editor):
    Ledger = apps.get_model('ledger', 'Ledger')
    Ledger.objects.update(number=models.F('id'))


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_auto_20160404_1246'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE'),
        migrations.AddField(
            model_name='ledger',
            name='number',
            field=models.PositiveIntegerField(
                default=1,
                help_text='Unique numeric identifier for this ledger',
            ),
        ),
        migrations.RunPython(
            set_ledger_number_field_to_primary_key_value,
        ),
        migrations.AlterField(
            model_name='ledger',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
