# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_auto_20160826_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='UUID for this ledger entry'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='UUID for this transaction'),
        ),
    ]
