# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_auto_20160829_0159'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ledger',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='entity_content_type',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='type',
        ),
    ]
