# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0016_auto_20160928_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
    ]
