# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0017_remove_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type2',
            new_name='type',
        ),
    ]
