# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_auto_20160928_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='action_type',
        ),
    ]
