# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ledger.models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_auto_20160928_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='action_type',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.ForeignKey(default=ledger.models.get_or_create_manual_transaction_type, on_delete=django.db.models.deletion.CASCADE, to='ledger.TransactionType'),
        ),
    ]
