# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0019_auto_20160929_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='creation_timestamp',
            new_name='created_at',
        ),
    ]
