# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-08 13:11
from __future__ import unicode_literals

import capone.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.ForeignKey(default=capone.models.get_or_create_manual_transaction_type_id, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capone.TransactionType'),
        ),
    ]
